// <auto-generated />
using System;
using ListingAutoPosterSandbox.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListingAutoPosterSandbox.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520035441_ReplaceSeedHomesWithYachts")]
    partial class ReplaceSeedHomesWithYachts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerageCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Builder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cabins")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Guests")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LengthFeet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Miami, FL",
                            BrokerageCompany = "YATCO Demo Brokerage",
                            Builder = "Sunseeker",
                            Cabins = 4,
                            Description = "A sleek motor yacht with modern entertaining spaces, refined interior finishes, expansive deck areas, and strong performance for coastal cruising.",
                            Guests = 8,
                            ImageUrl = "https://placehold.co/600x400?text=Azure+Horizon",
                            LengthFeet = 88m,
                            Location = "Miami, FL",
                            MaxSpeedKnots = 28m,
                            Price = 5495000m,
                            Title = "M/Y Azure Horizon",
                            YearBuilt = 2020
                        },
                        new
                        {
                            Id = 2,
                            Address = "Palm Beach, FL",
                            BrokerageCompany = "YATCO Demo Brokerage",
                            Builder = "Azimut",
                            Cabins = 4,
                            Description = "A well-appointed flybridge yacht designed for relaxed cruising, featuring generous outdoor lounging areas, a bright salon, and comfortable guest accommodations.",
                            Guests = 8,
                            ImageUrl = "https://placehold.co/600x400?text=Silver+Current",
                            LengthFeet = 72m,
                            Location = "Palm Beach, FL",
                            MaxSpeedKnots = 31m,
                            Price = 3250000m,
                            Title = "M/Y Silver Current",
                            YearBuilt = 2018
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fort Lauderdale, FL",
                            BrokerageCompany = "YATCO Demo Brokerage",
                            Builder = "Beneteau",
                            Cabins = 3,
                            Description = "A capable sailing yacht with clean lines, efficient handling, comfortable accommodations, and a practical layout suited for extended coastal passages.",
                            Guests = 6,
                            ImageUrl = "https://placehold.co/600x400?text=Wind+Meridian",
                            LengthFeet = 58m,
                            Location = "Fort Lauderdale, FL",
                            MaxSpeedKnots = 12m,
                            Price = 875000m,
                            Title = "S/Y Wind Meridian",
                            YearBuilt = 2019
                        });
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.PostAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduledPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledPostId");

                    b.ToTable("PostAttempts");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.ScheduledPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalPostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SocialAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("SocialAccountId");

                    b.ToTable("ScheduledPosts");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.SocialAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformAccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SocialAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo Facebook Page",
                            IsConnected = true,
                            Platform = "Facebook",
                            PlatformAccountId = "1103146319551782",
                            SecretName = "dev/social/facebook/demo-page",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo Instagram Business Account",
                            IsConnected = true,
                            Platform = "Instagram",
                            SecretName = "dev/social/instagram/demo-business",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Demo LinkedIn Company Page",
                            IsConnected = true,
                            Platform = "LinkedIn",
                            SecretName = "dev/social/linkedin/demo-company",
                            UpdatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.PostAttempt", b =>
                {
                    b.HasOne("ListingAutoPosterSandbox.Web.Models.ScheduledPost", "ScheduledPost")
                        .WithMany()
                        .HasForeignKey("ScheduledPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledPost");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.ScheduledPost", b =>
                {
                    b.HasOne("ListingAutoPosterSandbox.Web.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ListingAutoPosterSandbox.Web.Models.SocialAccount", "SocialAccount")
                        .WithMany()
                        .HasForeignKey("SocialAccountId");

                    b.Navigation("Listing");

                    b.Navigation("SocialAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
