// <auto-generated />
using ListingAutoPosterSandbox.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListingAutoPosterSandbox.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514200116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, Nashville, TN",
                            Description = "A bright two-bedroom condo near restaurants, shops, and public transit.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 425000m,
                            Title = "Modern Downtown Condo"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ridge Drive, Franklin, TN",
                            Description = "A spacious four-bedroom home with an open kitchen and fenced backyard.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 675000m,
                            Title = "Family Home with Large Backyard"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Cedar Lane, Murfreesboro, TN",
                            Description = "A low-maintenance townhome close to walking trails and local parks.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 350000m,
                            Title = "Quiet Townhome Near Parks"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
