// <auto-generated />
using System;
using ListingAutoPosterSandbox.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ListingAutoPosterSandbox.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514204929_AddPostAttempts")]
    partial class AddPostAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main Street, Nashville, TN",
                            Description = "A bright two-bedroom condo near restaurants, shops, and public transit.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 425000m,
                            Title = "Modern Downtown Condo"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Ridge Drive, Franklin, TN",
                            Description = "A spacious four-bedroom home with an open kitchen and fenced backyard.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 675000m,
                            Title = "Family Home with Large Backyard"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Cedar Lane, Murfreesboro, TN",
                            Description = "A low-maintenance townhome close to walking trails and local parks.",
                            ImageUrl = "https://placehold.co/600x400",
                            Price = 350000m,
                            Title = "Quiet Townhome Near Parks"
                        });
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.PostAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduledPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledPostId");

                    b.ToTable("PostAttempts");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.ScheduledPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalPostId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("ScheduledPosts");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.PostAttempt", b =>
                {
                    b.HasOne("ListingAutoPosterSandbox.Web.Models.ScheduledPost", "ScheduledPost")
                        .WithMany()
                        .HasForeignKey("ScheduledPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledPost");
                });

            modelBuilder.Entity("ListingAutoPosterSandbox.Web.Models.ScheduledPost", b =>
                {
                    b.HasOne("ListingAutoPosterSandbox.Web.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });
#pragma warning restore 612, 618
        }
    }
}
